server:
  port: 8080
  servlet:
    context-path: /

spring:
  profiles:
    include:
      - base-addi
  cache:
    type: redis
  jpa:
    open-in-view: false               # 영속성 컨텍스트의 생존 범위를 트랜잭션 범위로 한정
    generate-ddl: true
    show-sql: true                    # 콘솔창에 sql 출력
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    #        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        format_sql: true              # sql문 이쁘게 출력
        default_batch_fetch_size: 500 # 일대다 컬렉션 조회 시 성능 최적화 ( jpa 성능 개선을 위함 )
    defer-datasource-initialization: true
  sql:
    init:
      mode: never
